### ISSUE TITLE
このリポジトリは意図して`public`にしていますか？

### ISSUE THREAD

**Issue by ttoda31** [takenaka-ai/webapp-handson#1]
内部向けのように感じたため、質問です。

Docker周りの設定に気になる点があるので、IssueかPRに書いておこうかと思ったのですが、
「`private`の方が気楽に書きやすい」とのお気持ちもあります。

**Comment by toruinaba** [comment]
ハンズオンにあたってtakenaka-aiへの参加者が少なく、直前だったのもあっていったん引きやすいように```public```にしたのですが、```private```のほうが私も落ち着くので変更しようかなと思います！ありがとうございます！
